### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [fauzan121002/denovel#4]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

Ask me anything if you have some problem.

**Comment by fauzan121002** [comment]
> [Pagic](https://pagic.org) is a static site generator powered by Deno + React
> 
> Here are some demos:
> 
> * [pagic.org](https://pagic.org)
> * [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
> * [TypeScript 入门教程](https://ts.xcatliu.com/)
> 
> Ask me anything if you have some problem.

I will review it , thanks ! 😀

**Comment by fauzan121002** [comment]
I'm already review it but looks like i wouldn't add this on denovel , but thanks for submit this issue anyway.
